config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homepage#index'

  resources :reg_users, except: [:destroy]
  get   '/reg_users/:id/unsubscribe', to: 'reg_users#confirm_unsub'
  put   '/reg_users/:id/unsub', to: 'reg_users#unsub'
  
  resources :admin_users, only: [:index, :show, :new, :create]


  resources :sessions, only: [:new, :create]
  delete '/session', to: 'sessions#destroy'

  resources :events
  post '/events/:id/cancel', to: 'events#cancel'
  get  '/events/:id/adhoc_registration', to: 'events#adhoc_registration'
  post '/events/:id/adhoc_register', to: 'events#adhoc_register'
  
  resources :rsvps, only: [:destroy, :create, :new]
  get   '/rsvps/:id/cancel', to: 'rsvps#cancel'
  put   '/rsvps/:id/attended', to: 'rsvps#mark_attended'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_many :events
  has_secure_password

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :admin_user, optional: true
    has_many :rsvps

    def dt
        date_time.strftime("%d/%m/%Y %l:%M %P")
    end
end

app/models/homepage.rb
class Homepage < ApplicationRecord
end

app/models/reg_user.rb
class RegUser < ApplicationRecord
    # add in a has many for rsvps
    scope :subscribed, -> { where(active_sub: true) }
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :event
  belongs_to :reg_user
  
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
    before_action :authenticate!
  def index
		@admin_users = AdminUser.all
	end

	def show
		@admin_users = AdminUser.all
	end

  def new
    @admin_users = AdminUser.all
  end
  
  def create
 
  end

  private
  def admin_user_create_params
      params.require(:admin_user).permit(:email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  def authenticate!
    redirect_to "/" unless session[:admin_user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate!, except: [:show, :index ]

  def index
    @events = Event.where(active: true)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    #if logged_in?
    @event = Event.new
  end

  def create
    # redirect if logged_in?
    @event = Event.new(create_params)
    @event.active = true
    @event.cancelled = false
    if @event.save
        RegUser.subscribed.each do |user|
            EventMailer.new_event_email(@event, user).deliver_later
        end
        redirect_to events_path
    else
        render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(create_params)
    if @event.save
        redirect_to event_path(@event.id)
    else
        render :edit
    end
    #add redirect
  end

  def destroy
    #redirect_to'/' unless logged_in?
    event = Event.find(params[:id])
    event.active = false
    event.save
    redirect_to events_path
    #add redirect
  end

  def cancel
    event = Event.find(params[:id])
    event.cancelled = true
    event.save
  end

  def adhoc_registration
    @reg_user = RegUser.new
    @event = Event.find(params[:id])
  end

  def adhoc_register
    @event = Event.find(params[:id])
    @reg_user = RegUser.new(reg_user_create_params)
    @reg_user.active_sub = true
    if @reg_user.save
        Rsvp.create(
            reg_user: @reg_user,
            event: @event,
            active: true,
            attended: true
        )
        redirect_to event_path(@event.id)
    else
        render :adhoc_registration
    end
  end

  private
  
  def create_params
    params.require(:event).permit(:date_time, :address, :subject, :description)
  end

  def reg_user_create_params
    params.require(:reg_user).permit(:first_name, :last_name, :email, :school, :suburb, :contact_num)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end
end

app/controllers/reg_users_controller.rb
class RegUsersController < ApplicationController
    before_action :authenticate!, except: [ :unsubscribe, :new, :create ]

    def index
		@reg_users = RegUser.all
	end

	def show
		@reg_user = RegUser.find(params[:id])
	end

	def new
		@reg_user = RegUser.new
    end

    def edit
        @reg_user = RegUser.find(params[:id])
    end
    
    def update
        @reg_user = RegUser.find(params[:id])
        @reg_user.update_attributes(create_params)
        if @reg_user.save
            redirect_to reg_user_path(@reg_user.id)
        else
            render :edit
        end
    end
    
    def confirm_unsub
		@reg_user = RegUser.find(params[:id])
    end

    def unsub
        @reg_user = RegUser.find(params[:id])
        @reg_user.active_sub = false
        @reg_user.save
        redirect_to reg_user_path(@reg_user.id)
	end

	def create
		@reg_user = RegUser.new(create_params)
		@reg_user.active_sub = true
        if @reg_user.save
            RegUserMailer.welcome_email(@reg_user).deliver_later
            @message = "Thanks for signing up as a volunteer #{@reg_user.first_name}, be sure to check your emails to keep up to date with our latest events."
    		render :template => 'homepage/index'
        else
            render :new
        end
	end

	  private

	  def create_params
	    params.require(:reg_user).permit(:first_name, :last_name, :email, :school, :suburb, :contact_num)
	  end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
    before_action :authenticate!, only: [:mark_attended ]
  def index
    @rsvps = Rsvp.all
  end

  def show
    @rsvp = Rsvp.find(params[:id])
  end

  def new
    @rsvp = Rsvp.new
    @event = Event.find(params[:event_id])
    @reg_user = RegUser.find(params[:reg_user_id])
    
  end

  def create
    
    @rsvp = Rsvp.new(create_params)
    @event = @rsvp.event
    @reg_user = @rsvp.reg_user
    @rsvp.active = true
    if @rsvp.save 
        RsvpMailer.rsvp_email(@rsvp).deliver_later
        @message = "Thank you!! You're now registered to go to #{@event.subject}"
        render :template => 'homepage/index'
    else
        @message = @rsvp.errors.full_messages
        render :new
    end

    #replace above with correct redirect route if saved
    # if @rsvp.save
    #   redirect_to '/rsvps/get'
    # end
  end


  def cancel
    @rsvp = Rsvp.find(params[:id])
  end

  def destroy
    rsvp = Rsvp.find(params[:id])
    rsvp.active = false
    if rsvp.save
        RsvpMailer.cancel_confirm_email(rsvp).deliver_later
        @message = "You're no longer attending #{rsvp.event.subject}, thanks for keeping us updated."
    end
    render :template => 'homepage/index'
  end

  def mark_attended
    rsvp = Rsvp.find(params[:id])
    rsvp.attended = true
    rsvp.save
    redirect_to event_path(rsvp.event.id)
  end

  private
  
  def create_params
    params.require(:rsvp).permit(:reg_user_id, :event_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :authenticate!, only: [ :destroy ]
  def new
  end

  def create
    admin_user = AdminUser.find_by(email: params[:session][:email])
    if admin_user && admin_user.authenticate(params[:session][:password])
      session[:admin_user_id] = admin_user.id
      redirect_to '/reg_users'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      redirect_to '/'
    end
  end

  def destroy
    current_user == nil
    session[:admin_user_id] = nil
    redirect_to '/'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(admin_user)
    session[:admin_user_id] = admin_user.id
  end

  def current_user
    if session[:admin_user_id]
      @current_user ||= AdminUser.find_by(id: session[:admin_user_id])
    end
  end
end

app/views/admin_users/new.html.erb
<div class="login-title">
    <h1 class="h1-login">sign up</h1>
</div>

<div class="box-container">
    <%= form_tag "/admin_users", method: 'post' do %>
        <label class="form-label"for="">email </label>
        <input class="input-box" type="text" name="email">

        <label class="form-label" for="">password</label>
        <input class="input-box" type="password" name="password">

        <button class="submit-btn">sign up</button>
    <% end %> 
</div>

app/views/email_partials/_email_style.html.erb
<style> 
/* email footer */
.email-footer {
  text-align: center;
}

.privacy-policy {
  color: #FC0D1B;
  font-size: 14px;
}

.unsubscribe-link a{
  color: gray;
  font-size: 10px;
  text-decoration: none;
}


/* email header */

.email-logo {
  max-width: 80%;
  vertical-align: center;
  margin-left: 10%;
}

/* email assistance note */
.email-assist-wrapper {
  display: flex;
  max-width: 90%;
  margin:auto; 
}

.email-assist-image {
  flex:1; 
}
.email-assist-image img{
  height:70%;
  width: 70%;
  padding: 10%;
}

.email-assist-text {
  flex:3;
}

/* link box */
.event-link-box {
  background-color: #FC0D1B;
  max-width: 75%;
  margin-left: 10%;
  padding: 5px;
  text-align: center;
}

.event-link-box a{
  color: white;
  text-align: center;
}



.impact-text {
  font-weight: 600; 
} 
</style>

app/views/email_partials/_html_copyr_footer.html.erb
    <div class="email-footer">
        <span>&copy; 2018 Copyright Impact  -
            <span class="privacy-policy">Terms and Conditions - Privacy Policy</span>
        </span>
        <span class="unsubscribe-link"><%= link_to "Unsubscribe", "https://#{ENV['HOST_URL']}/reg_users/#{uid}/unsubscribe" %></span>
    </div>

app/views/email_partials/_html_header.html.erb
    <div class="email-logo">
        <%= image_tag attachments['impact-red-logo.svg'].url %>
    </div>

app/views/email_partials/_html_help_section.html.erb
<div class="email-assist-wrapper">
    <div class="email-assist-image">
        <%= image_tag attachments['help.svg'].url %>
    </div>
    <div class="email-assist-text">
        <h1>Need help?</h1>
        <p class="email-assist-contact">If you require any assistance, or have any questions, please contact: help@impact.org.au</p>
    <div>
</div>

app/views/events/adhoc_registration.html.erb
<div class="rego-wrapper">
  <p class="rego">Register a new user as attending <%= @event.subject %></p>

  <%= simple_form_for @reg_user, :url => url_for(:action => 'adhoc_register', :controller => 'events'), :method => 'post' do |f| %>

    <%= f.input :first_name, label: false, error: 'Please enter your first name' %>
    <%= f.input :last_name, label: false, error: 'Please enter your last name' %>
    <%= f.input :email, label: false %>

    <input type="checkbox" name="" value="" id="sixteen">
    <label> I am 16 years or under</label>

    <div class="student hidden" >
      <%= f.input :school, label: false %>
      <%= f.input :suburb, label: false %>
    </div>
    <%= f.input :contact_num, label: false %>
    <%= f.button :submit, "Register as attending", :class => "reg-button" %>

  <% end %>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>

  var studentDiv = document.querySelector(".student")
  var checkboxStudent = document.querySelector("#sixteen")
  $(checkboxStudent).on('change', function() {     
     $(studentDiv).toggleClass('hidden');        
});



</script>

app/views/events/edit.html.erb
<div class="event-edit">

<p>Edit event below.</p>

<%= simple_form_for @event,  :method => 'put' do |f| %>
    <%= f.input :date_time, label: 'Your username please', error: 'Date and time mandatory, please make sure you enter them.' %>
    <%= f.input :address %>
    <%= f.input :subject %>
    <%= f.input :description, inline_label: 'This will appear on the email' %>
    <%= f.button :submit, :class => "reg-button" %>
<% end %>

</div>

app/views/events/index.html.erb
<%  if  session[:admin_user_id] %>
    <div class="new-event-btn">
        <%= link_to "Add New Event", new_event_path, :class => "reg-button" %>
    </div>
<% end %>

<table class="reg-table">
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Subject</th>
        <th>Location</th>
        <th colspan=4></th>
    </tr>
    <% @events.each do |event| %>
    <tr>
        <td><%= event.date_time.strftime("%d/%m/%Y") %></td>
        <td><%= event.date_time.strftime("%l:%M %P") %></td>
        <td><%= event.subject %></td>
        <td><%= event.address %></td>
        <td><%= link_to 'Show', event_path(event.id) %></td>
        <% if session[:admin_user_id] %>
            <td><%= link_to 'Edit', edit_event_path(event.id)%></td>
            <td>
                <%= form_tag "/events/#{event.id}", method: 'delete' do %>
                    <button class="submit-btn">Delete</button>
                <% end %> 
            </td>
        
            <td>
                <%= form_tag "/events/#{event.id}/cancel", method: 'post' do %>
                    <button class="submit-btn">Cancel</button>
                <% end %> 
            </td>
        <% end %>
    </tr>
    <% end %>
</table>

app/views/events/new.html.erb
<div class="event-new">

<p>Create your new <span class="bold">impact</span> event below.</p>

<%= simple_form_for @event, :method => 'post' do |f| %>
    <%= f.input :date_time, label:false, error: 'Date and time mandatory, please make sure you enter them.' %>
    <%= f.input :address, label:false, :class => "text-input"%>
    <%= f.input :subject, label:false %>
    <%= f.input :description, label:false, inline_label: 'This will appear on the email', :class => "text-input" %>
    <%= f.button :submit, :class => "reg-button" %>
<% end %>

</div>

app/views/events/partials/_view_attendees.html.erb
<h2 class="event-h2"> Attendees <span>(<%= @event.rsvps.length %>)</span></h2>

<% if  session[:admin_user_id] %>
  <div class="btn-containers">
    <a href="" class="reg-button rsvp-reg-btn no-rsvp-btn">View registered volunteers who didn't RSVP</a>
    <a href="/events/<%= @event.id %>/adhoc_registration" class="reg-button rsvp-reg-btn">Register and RSVP new volunteers</a>
  </div>

  <div class="att-flex">
        <% @event.rsvps.each do |rsvp| %>
        <div class="attendees">
          <div class="attendees-left">
            <p class="event-p"><%= rsvp.reg_user.first_name %> <%= rsvp.reg_user.last_name %></p>
            <p class="event-p"><%= rsvp.reg_user.email %></p>
            <p class="event-p"><%= rsvp.reg_user.contact_num %></p>
          </div>
          
          
          <div class="attendees-right">
                <% unless rsvp.attended %>
                    <%= form_tag "/rsvps/#{rsvp.id}/attended", method: 'put' do %>
                        <button class="submit-btn">Mark Present</button>
                    <% end %> 

                <% else %>
                    Attending
                <% end %>
                

          </div>

        </div>
        <% end %>

<% else %>
   <p>You can only view attendees if you're logged in as an admin</p>
<% end %>




<script>
  console.log('caroline test!!')
  var clicked_email;

  var attendeesContainer = document.querySelector('.att-flex')
  

  attendeesContainer.addEventListener('click',function(e){
    if (e.target.className.includes('container-cbox')){
     var text = e.target.parentNode.firstChild.nextSibling.innerHTML

    // console.log(e.target.parentNode.firstChild.nextSibling.innerHTML)
    // console.log(clicked_email)
     e.target.parentNode.parentNode.classList.toggle('color-chk')
    //  e.target.parentNode.firstChild.nextSibling.classList.toggle('color-chk')
    text = "Attended"
    
  
      // e.target.classList.toggle('color-ch')
    }
    
    
  })
</script>

app/views/events/show.html.erb
<h1>Event Details: <%= @event.subject %></h1>
<div class="show-event">
  <div class="event-details">
    <h4 class="event-h4">Date and Time:</h4>
    <%= @event.dt %> |

    <h4 class="event-h4">Address:</h4>
    <%= @event.address %> |

    <h4 class="event-h4">Description:</h4>
    <%= @event.description %> |

    <h4 class="event-h4"> Created By:</h4>
    <%= @event.admin_user.full_name if @event.admin_user.present? %> | 

<% if  session[:admin_user_id] %>
    <%= link_to "edit", edit_event_path(@event.id) %>

    <%= form_tag "/events/#{@event.id}", method: 'delete' do %>
      <button class="submit-btn">Delete</button>
    <% end %> 

    <%= form_tag "/events/#{@event.id}/cancel", method: 'post' do %>
      <button class="submit-btn">Cancel</button>
    <% end %> 
<% end %>
  </div>

  <div class="attendees-box">
    <%= render "events/partials/view_attendees" %>
  </div>
</div>

app/views/homepage/index.html.erb
<div>
    <%= @message if @message.present? %>
</div>

<div class="homepage-wrapper">
	<h1 class="homepage">Welcome!</h1>

	<h2 class="homepage">Thank you for your interest in volunteering with <span class="bold">impact</span>.</h2>

	<p><span class="bold">impact</span> is a volunteer run organisation providing assistance to women and children fleeing extreme violence at home via agencies delivering crisis accommodation.</p>

	<p class="highlight">We are always looking for new volunteers. <br>Please click below to <span class="homepage">register for emails</span> about our upcoming events and volunteer opportunities.</p>

	<a href="/reg_users/new" class="reg-button">Click here to register.</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>impact</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Niramit" rel="stylesheet">
  </head>

  <body>
    <header>
        <div class="app-image">
            <a href="/"><%= image_tag "/impact-red-logo.svg" %></a>
        </div>
        <nav>
            <ul>
                <li>
                    <%= link_to 'Home', '/' %>
                </li>
                <li>
                    <%= link_to 'Events', events_path %>
                </li>
                 <% if  !session[:admin_user_id] %>
                    <li>
                        <%= link_to 'Register', new_reg_user_path %>
                    </li>
                <% end %>
                <% if  session[:admin_user_id] %>
                    <li>
                        <%= link_to 'All Volunteers', reg_users_path %>
                    </li>
                    <li>
                        <%= link_to 'Sign Out', session_path,:method => :delete %>
                    </li>
                <% end %>
            </ul>
        </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/reg_users/confirm_unsub.html.erb
<h1>You are about to unsubscribe from our emails...</h1>

<p>
    We hate to see you go <%= @reg_user.first_name %>, but if you would like to take a break from receiving our emails click the link below.
</p>

<%= form_tag "/reg_users/#{@reg_user.id}/unsub", method: 'put' do %>
    <button class="submit-btn">unsubscribe</button>
<% end %> 

app/views/reg_users/edit.html.erb
<div class="rego-wrapper">

  <%= simple_form_for @reg_user, :method => 'put' do |f| %>
    <%= f.input :first_name, label: false, error: 'Please enter first name' %>
    <%= f.input :last_name, label: false, error: 'Please enter last name' %>
    <%= f.input :email, label: false %>

    <div class="student" >
      <%= f.input :school, label: false %>
      <%= f.input :suburb, label: false %>
    </div>
    <%= f.input :contact_num, label: false %>

    <br>

    <%= f.button :submit, "Save" %>

  <% end %>
</div>

app/views/reg_users/index.html.erb
<%# #if logged in %>

<h2>Registered Volunteers</h2>

<p>Listed below are the details for those who have registered for emails. Click on <span class="bold">Last Name</span> or <span class="bold">Active</span> to sort the list.</p>

<a class="red" href="/reg_users/new">Register a new volunteer!</a>

<table class="reg-table">
  <tr>
	<th onclick="sortTable(0)" class="pointer">Active (click to sort)</th>
    <th>First Name</th>
	<th onclick="sortTable(2)" class="pointer">Last Name (click to sort)</th>
    <th>Email</th>
    <th>Contact Number</th>
    <th>School</th>
    <th>Suburb</th>
    <th></th>
  </tr>
	<% @reg_users.each do |user|%>
  <tr>

    <td> <%= user.active_sub ? "Yes" : "No" %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td>+61 <%= user.contact_num %></td>
    <td><%= user.school %></td>
    <td><%= user.suburb %></td>
    <td><%= link_to "Show", reg_user_path(user.id) %></td>
  </tr>
<% end %>  
</table>


<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.querySelector(".reg-table");
  switching = true;
  // Set the sorting direction to ascending:
  dir = "asc"; 
  /* Make a loop that will continue until
  no switching has been done: */
  while (switching) {
    // Start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /* Loop through all table rows (except the
    first, which contains table headers): */
    for (i = 1; i < (rows.length - 1); i++) {
      // Start by saying there should be no switching:
      shouldSwitch = false;
      /* Get the two elements you want to compare,
      one from current row and one from the next: */
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /* Check if the two rows should switch place,
      based on the direction, asc or desc: */
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /* If a switch has been marked, make the switch
      and mark that a switch has been done: */
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      // Each time a switch is done, increase this count by 1:
      switchcount ++; 
    } else {
      /* If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again. */
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}
</script>

app/views/reg_users/new.html.erb
<div class="rego-wrapper">
  <p class="rego">We love welcoming new volunteers! <br>Register here for info on our events.</p>

  <%= simple_form_for @reg_user, :method => 'post' do |f| %>
    <%= f.input :first_name, label: false, error: 'Please enter your first name' %>
    <%= f.input :last_name, label: false, error: 'Please enter your last name' %>
    <%= f.input :email, label: false %>

    <input type="checkbox" name="" value="" id="sixteen">
    <label> I am 16 years or under</label>

    <div class="student hidden" >
      <%= f.input :school, label: false %>
      <%= f.input :suburb, label: false %>
    </div>
    <%= f.input :contact_num, label: false %>
    <%= f.button :submit, "Register to receive emails", :class => "reg-button" %>

  <% end %>

  <% if  session[:admin_user_id] %>
    <a href="/reg_users">See list of all registered volunteers.</a>
  <% end %>
  
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>

  var studentDiv = document.querySelector(".student")
  var checkboxStudent = document.querySelector("#sixteen")
  $(checkboxStudent).on('change', function() {     
     $(studentDiv).toggleClass('hidden');        
});



</script>

app/views/reg_users/show.html.erb
<%# #if logged in %>

<div class="user-wrapper">
	<div class="user-details">
		<h2><%= @reg_user.first_name %> <%= @reg_user.last_name %></h2>

		<ul class="user-edit-sub">
				<li>
						<%= link_to 'Edit me', edit_reg_user_path(@reg_user.id) %>
				</li>
				<li>
						<%= form_tag "/reg_users/#{@reg_user.id}/unsub", method: 'put' do %>
				<button class="submit-btn reg-button">unsubscribe user</button>
		<% end %> 
				</li>
		</ul>

		<p>
				<strong>First Name</strong>
				<%= @reg_user.first_name %>
		</p>

		<p>
				<strong>Last Name</strong>
				<%= @reg_user.last_name %>
		</p>

		<p>
				<strong>Email</strong>
				<%= @reg_user.email %>
		</p>

		<p>
				<strong>Best Contact #</strong>
				<%= @reg_user.contact_num %>
		</p>

		<p>
				<strong>School</strong>
				<%= @reg_user.school %>
		</p>

		<p>
				<strong>School Suburb</strong>
				<%= @reg_user.suburb %>
		</p>

		<p>
				<strong>Currently Subscribed?</strong>
				<%= @reg_user.active_sub ? "Yes" : "No" %>
		</p>
	</div>
</div>

app/views/rsvps/cancel.html.erb
<h1> Cancel your RSVP to <%= @rsvp.event.subject %> </h1>
<h2> Hi <%=@rsvp.reg_user.first_name%>, would you like to cancel your RSVP to <%= @rsvp.event.subject %> on <%= @rsvp.event.dt %>? </h2>

<%= @rsvp.reg_user.id %>
<%= @rsvp.event.id %>
<%= simple_form_for @rsvp, :method => 'delete' do |f| %>
    <%= f.button :submit, "Yes, I'm unable to attend!" %>
<% end %>

app/views/rsvps/new.html.erb
<h1> RSVP to <%= @event.subject %> </h1>
<h2> Hi <%=@reg_user.first_name%>, will you be attending <%= @event.subject %> on <%= @event.dt %>?  </h2>

<%= @reg_user.id %>
<%= @event.id %>
<%= simple_form_for @rsvp, :method => 'post' do |f| %>
    <%=f.hidden_field :reg_user_id, :value => @reg_user.id %>
    <%=f.hidden_field :event_id, :value => @event.id %>
    <%= f.button :submit, "Yes, I'm attending!" %>
<% end %>